name: stock_investment_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  postgres: ^2.4.3
  email_validator: '^2.1.16'
  flutter_pw_validator: 
  

  # Common
  nb_utils: ^4.6.25
  cached_network_image: ^3.2.3
  fl_chart: 0.36.1
  url_launcher: ^6.1.6

  # State Management
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  postgres: ^2.6.1  
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true
  assets:
    - assets/stock/
    - assets/icons/
    - assets/images/app/
